// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsJUQZvZt1fA86t6C5OXukx4F2oNbFB9k',
    appId: '1:1045283753150:web:54d1e1a085c608ea2f62ef',
    messagingSenderId: '1045283753150',
    projectId: 'fyp2-25e88',
    authDomain: 'fyp2-25e88.firebaseapp.com',
    storageBucket: 'fyp2-25e88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYEhd8bLI5-TONMzuHyPtejOoTgzw_fIw',
    appId: '1:1045283753150:android:06379f32b27b3a812f62ef',
    messagingSenderId: '1045283753150',
    projectId: 'fyp2-25e88',
    storageBucket: 'fyp2-25e88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfeNVaM-ms9Zl3pNMkLjcbTBZVGVsITvE',
    appId: '1:1045283753150:ios:ec374ece765942662f62ef',
    messagingSenderId: '1045283753150',
    projectId: 'fyp2-25e88',
    storageBucket: 'fyp2-25e88.firebasestorage.app',
    iosBundleId: 'com.example.fyp2App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfeNVaM-ms9Zl3pNMkLjcbTBZVGVsITvE',
    appId: '1:1045283753150:ios:ec374ece765942662f62ef',
    messagingSenderId: '1045283753150',
    projectId: 'fyp2-25e88',
    storageBucket: 'fyp2-25e88.firebasestorage.app',
    iosBundleId: 'com.example.fyp2App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsJUQZvZt1fA86t6C5OXukx4F2oNbFB9k',
    appId: '1:1045283753150:web:3068aac5ff09bc252f62ef',
    messagingSenderId: '1045283753150',
    projectId: 'fyp2-25e88',
    authDomain: 'fyp2-25e88.firebaseapp.com',
    storageBucket: 'fyp2-25e88.firebasestorage.app',
  );

}